### ISSUE TITLE
When apply Points then alert pop-up is displaying

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/points-and-rewards-for-woocommerce#101]
When applying Points then alert pop-up is displaying
![image](https://user-images.githubusercontent.com/25762796/75433097-6e03a600-5975-11ea-88fe-17e888a52b7c.png)

**Comment by Snehlata-Sharma** [comment]
fixed

**Comment by anshucedcoss** [comment]
Fixed
