### ISSUE TITLE
When assigined points to the variable product then it's not displaying properly

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/points-and-rewards-for-woocommerce#102]
When assigned points to the variable product then it's not displaying properly
![image](https://user-images.githubusercontent.com/25762796/76067159-f2c57400-5fb4-11ea-9d35-3a0dc5056248.png)

**Comment by Snehlata-Sharma** [comment]
fixed

**Comment by anshucedcoss** [comment]
Done
