### ISSUE TITLE
Sufficient spelling is wrong on the cart page

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/points-and-rewards-for-woocommerce#103]
Sufficient spelling is wrong on the cart page
![image](https://user-images.githubusercontent.com/25762796/76502083-6c53db00-6469-11ea-8e69-fbcb86f3a7e4.png)

**Comment by Snehlata-Sharma** [comment]
fixed

**Comment by anshucedcoss** [comment]
Done
