### ISSUE TITLE
Customer is getting product assigned points multiple time if completed the order status multiple time

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/points-and-rewards-for-woocommerce#104]
Customer is getting product assigned points multiple time if completed the order status multiple time
![image](https://user-images.githubusercontent.com/25762796/76505700-ea1ae500-646f-11ea-882c-fddb25024982.png)

**Comment by Snehlata-Sharma** [comment]
fixed

**Comment by anshucedcoss** [comment]
Done
