### ISSUE TITLE
When share the referral link on WhatsApp then redirecting to the error pageWhen share referral link on WhatsApp then redirecting to error page

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/points-and-rewards-for-woocommerce#108]
When share the referral link on WhatsApp then redirecting to the error page

![image](https://user-images.githubusercontent.com/25762796/83243084-0b5fb780-a1bb-11ea-8c00-d1cd75521805.png)

**Comment by Snehlata-Sharma** [comment]
fixed

**Comment by anshucedcoss** [comment]
DONE
