### ISSUE TITLE
After assigin point to the product when update quanity from the cart then assigined points are not increasing

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/points-and-rewards-for-woocommerce#109]
After assign point to the product when update quanity from the cart then assigined points are not increasing
![image](https://user-images.githubusercontent.com/25762796/83243297-55489d80-a1bb-11ea-9869-529e7f1c217c.png)

![image](https://user-images.githubusercontent.com/25762796/83243391-73160280-a1bb-11ea-97e1-e0134421be67.png)

**Comment by Snehlata-Sharma** [comment]
fixed

**Comment by anshucedcoss** [comment]
DONE
