### ISSUE TITLE
No need of shop page and account page on popup

### ISSUE THREAD

**Issue by anshucedcoss** [Makewebbetter/points-and-rewards-for-woocommerce#119]
No need of shop page and account page on popup

![image](https://user-images.githubusercontent.com/25762796/96715632-81aac380-13c1-11eb-8518-2922920827d7.png)

![image](https://user-images.githubusercontent.com/25762796/96715911-e5cd8780-13c1-11eb-9c9d-a76b7cc34d6b.png)

**Comment by indresh-cedcoss** [comment]
fixed

**Comment by anshucedcoss** [comment]
DONE
