### ISSUE TITLE
Enable apply points during checkout are not working.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/points-and-rewards-for-woocommerce#127]
**Bug Name -** Enable apply points during checkout are not working.
**Area Path -**
**Status -** New
**Woo Commerce Version -** 5.5.2
**WordPress Version -** 5.8.0
**Plugin Version -** 1.1.4
**Description -**

Enable apply points during checkout are not working without selecting Redemption Over Cart Sub-Total.

https://www.awesomescreenshot.com/image/11667907?key=43b3bf7467cbf24dddeb0d9b9473cc4a

https://www.awesomescreenshot.com/image/11667913?key=139bd520ff73040971d564015bfa079a

**Comment by prince-cedcoss** [comment]
issue is fixed please checked

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok

**Comment by prince-cedcoss** [comment]
fixed the issue please check!

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
