### ISSUE TITLE
Please reverse the setting of Earn Points Per Currency Settings.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/points-and-rewards-for-woocommerce#128]
**Bug Name -** Please reverse the setting of Earn Points Per Currency Settings.
**Area Path -**
**Status -** New
**Woo Commerce Version -** 5.5.2
**WordPress Version -** 5.8.0
**Plugin Version -** 1.1.4
**Description -**

![image](https://user-images.githubusercontent.com/76723393/128598827-4f1425ff-5def-4f8a-8ce0-8a7acdfc0294.png)

**Comment by prince-cedcoss** [comment]
issue is fixed please checked

**Comment by AnuraktSachan-CEDCOSS** [comment]
![image](https://user-images.githubusercontent.com/76723393/133785888-1269c979-5bd5-417f-8a84-d337d0b359c7.png)


![image](https://user-images.githubusercontent.com/76723393/133785900-bf5d7201-95a3-4b3f-ada9-9126b3d71852.png)

**Comment by prince-cedcoss** [comment]
fixed the issue please check!

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
