### ISSUE TITLE
Issue in Select Color Notification Bar

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/points-and-rewards-for-woocommerce#129]
**Bug Name -** Issue in Select Color Notification Bar
**Area Path -**
**Status -** New
**Woo Commerce Version -** 5.5.2
**WordPress Version -** 5.8.0
**Plugin Version -** 1.1.4
**Description -**

![image](https://user-images.githubusercontent.com/76723393/128600902-1e5952b5-3ddb-4e2b-a131-ccbc98f426d4.png)

![image](https://user-images.githubusercontent.com/76723393/128600897-0b90e4e1-52f0-4584-9fdc-ddde543e601b.png)

![image](https://user-images.githubusercontent.com/76723393/128600890-0b6029c7-f4cf-4a55-83fa-5f39f6a1e02c.png)

**Comment by prince-cedcoss** [comment]
issue is fixed please checked

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
