### ISSUE TITLE
Design issue in social media icons.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/points-and-rewards-for-woocommerce#130]
**Bug Name -** Design issue in social media icons.
**Area Path -**
**Status -** New
**Woo Commerce Version -** 5.5.2
**WordPress Version -** 5.8.0
**Plugin Version -** 1.1.4
**Description -**

![image](https://user-images.githubusercontent.com/76723393/128622132-8848fc65-768e-4762-9fb3-55d30e75852a.png)

**Comment by prince-cedcoss** [comment]
issue is fixed please checked!

**Comment by AnuraktSachan-CEDCOSS** [comment]
ok
