### ISSUE TITLE
QA Issues.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/points-and-rewards-for-woocommerce#135]
**Bug Name -** QA Issues.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 5.9.0
**WordPress Version -** 5.8.2
**Plugin Version -**
**Description -**

Update WC & WP 
Update Plugin version.

PHPCS
[points-and-rewards-for-woocommerce.docx](https://github.com/Makewebbetter/points-and-rewards-for-woocommerce/files/7528218/points-and-rewards-for-woocommerce.docx)

**Comment by aakash-cedcoss** [comment]
done

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
