### ISSUE TITLE
QA issues

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/points-and-rewards-for-woocommerce#137]
**Bug Name -** QA issues
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.0.0
**WordPress Version -** 5.8.2
**Plugin Version -** 
**Description -**

Update required data.

**Comment by prince-cedcoss** [comment]
issue were fixed!

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
