### ISSUE TITLE
Language Issue.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/points-and-rewards-for-woocommerce#140]
**Bug Name -** Language Issue.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.0.1
**WordPress Version -** 5.8.2
**Plugin Version -** 
**Description -**

IMPORTANT NOTICE: is not translated.

**Comment by aakash-cedcoss** [comment]
Notice need not be translated

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
