### ISSUE TITLE
Document is redirect to gift card free version

### ISSUE THREAD

**Issue by cedcoss-pooja** [MakeWebBetter/points-and-rewards-for-woocommerce#3]
Bug name:-Documentation button is redirect into giftcard 
Area Path: admin-dashboard>woocommerce>rewardeem woocommerce points and rewards>documentation button
Build Number:/Version Number 1.0.0
Status: New
Environment: LinuxMint 17.2/phpmyadmin
Description:When we click on the documentation button then redirect to giftcard plugin page

**Comment by cedcoss-pooja** [comment]
not fixed

**Comment by mohitmishra-cedcoss** [comment]
Fixed
