### ISSUE TITLE
"Apply Points" are accepting Negative value

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/points-and-rewards-for-woocommerce#71]
"Apply Points" are accepting Negative value.
![image](https://user-images.githubusercontent.com/25762796/68399251-25449900-019c-11ea-9339-895f128c6bec.png)

**Comment by mohitmishra-cedcoss** [comment]
Done

**Comment by anshucedcoss** [comment]
Still accepting 
![image](https://user-images.githubusercontent.com/25762796/68649166-05b8c200-0548-11ea-811d-0366c5ca0433.png)

**Comment by mohitmishra-cedcoss** [comment]
Done
