### ISSUE TITLE
WhatsApp Sharing Button isn't displaying Fine

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/points-and-rewards-for-woocommerce#97]
WhatsApp Sharing Button isn't displaying Fine.

![image](https://user-images.githubusercontent.com/25762796/75339299-3f72c600-58b6-11ea-804d-53c6e51a7629.png)

**Comment by Snehlata-Sharma** [comment]
FIXED

**Comment by anshucedcoss** [comment]
DONE
