### ISSUE TITLE
Wrong referral sharing is generating

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/points-and-rewards-for-woocommerce#98]
Wrong referral sharing is generating.
![image](https://user-images.githubusercontent.com/25762796/75339652-f111f700-58b6-11ea-8830-07b31fd09731.png)

![image](https://user-images.githubusercontent.com/25762796/75339665-f707d800-58b6-11ea-91c9-62664f97f856.png)

**Comment by Snehlata-Sharma** [comment]
fixed

**Comment by anshucedcoss** [comment]
DONE
