### ISSUE TITLE
Need to update "Referral Earns" Heading in Points Log

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/points-and-rewards-for-woocommerce#99]
Need to update "Referral Earns" Heading in Points Log
![image](https://user-images.githubusercontent.com/25762796/75340730-0851e400-58b9-11ea-9736-7bb4ec171aec.png)

![image](https://user-images.githubusercontent.com/25762796/75340861-44854480-58b9-11ea-8acf-179adb4b5448.png)

![image](https://user-images.githubusercontent.com/25762796/75341183-e73dc300-58b9-11ea-91ac-741d4c2db4fa.png)

**Comment by Snehlata-Sharma** [comment]
fixed

**Comment by anshucedcoss** [comment]
DONE
